# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create Teams [Devops, Dev and Testing] with appropriate permissions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Get Repros
      run: curl -u ${{secrets.USR_NAM}}:${{secrets.PASS}} -H "Accept:application/vnd.github.v3+json" https://api.github.com/users/rimi-345/repos
    - name: Create Devops Team
      run: curl -X POST -H "Accept:application/vnd.github.v3+json" -H "Authorization:${{ secrets:PASS }}" https://api.github.com/orgs/ajaykatke2005/teams -d '{"name":"Devops"}'

