# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven


on:
  push:
    branches:
      - disable2
      
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Creating a Repo
      run: | 
        echo "Login to git api "
        curl -i -u ${{ secrets.GITHUBUSER }}:${{ secrets.GITHUBPASS }} https://api.github.com/user
        echo "create a new repo"
        curl \-X POST \-H "Accept: application/vnd.github.v3+json" \-H "Authorization: token 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" \https://api.github.com/user/repos\-d '{"name":"disable merge","allow_merge_commit":false,"allow_squash_merge":true,"allow_rebase_merge":false}' 
        echo "completed"
